<a href="https://colab.research.google.com/github/kunalga/pythonEveryDay/blob/main/day21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('/content/Customer_Churn_Modelling.csv')

In [ ]:
data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
data.to_csv('Modelling.csv',index= False)

In [ ]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
data.tail()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
data.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [ ]:
list(data.columns)

['RowNumber',
 'CustomerId',
 'Surname',
 'CreditScore',
 'Geography',
 'Gender',
 'Age',
 'Tenure',
 'Balance',
 'NumOfProducts',
 'HasCrCard',
 'IsActiveMember',
 'EstimatedSalary',
 'Exited']

In [ ]:
data[['Age']]

      Age
0      42
1      41
2      42
3      39
4      43
...   ...
9995   39
9996   35
9997   36
9998   42
9999   28

[10000 rows x 1 columns]

In [ ]:
# Instead of this URL:
# "https://github.com/laxmimerit/All-CSV-ML-Data-Files-Download/blob/master/Customer_Churn_Modelling.csv"

# Use the 'raw' URL for the CSV file:
url = "https://raw.githubusercontent.com/laxmimerit/All-CSV-ML-Data-Files-Download/master/Customer_Churn_Modelling.csv"
data = pd.read_csv(url)

In [ ]:
data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
data2 = pd.read_html("https://www.basketball-reference.com/leagues/NBA_2015_totals.html")

In [ ]:
type(data2)

list

In [ ]:
len(data2)

2

In [ ]:
data2[0]

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,Awards
0,1.0,James Harden,25.0,HOU,SG,81.0,81.0,2981.0,647.0,1470.0,...,384.0,459.0,565.0,154.0,60.0,321.0,208.0,2217.0,4.0,"MVP-2,AS,NBA1"
1,2.0,Stephen Curry,26.0,GSW,PG,80.0,80.0,2613.0,653.0,1341.0,...,285.0,341.0,619.0,163.0,16.0,249.0,158.0,1900.0,0.0,"MVP-1,AS,NBA1"
2,3.0,Russell Westbrook,26.0,OKC,PG,67.0,67.0,2302.0,627.0,1471.0,...,364.0,488.0,574.0,140.0,14.0,293.0,184.0,1886.0,11.0,"MVP-4,AS,NBA2"
3,4.0,LeBron James,30.0,CLE,SF,69.0,69.0,2493.0,624.0,1279.0,...,365.0,416.0,511.0,109.0,49.0,272.0,135.0,1743.0,2.0,"MVP-3,DPOY-13,AS,NBA1"
4,5.0,Damian Lillard,24.0,POR,PG,82.0,82.0,2925.0,590.0,1360.0,...,329.0,378.0,507.0,97.0,21.0,222.0,164.0,1720.0,0.0,AS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
647,489.0,Malcolm Lee,24.0,PHI,SG,1.0,0.0,2.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
648,490.0,Kalin Lucas,25.0,MEM,PG,1.0,0.0,6.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,NaN
649,491.0,Ronny Turiaf,32.0,MIN,C,2.0,0.0,19.0,0.0,0.0,...,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
650,492.0,David Wear,24.0,SAC,PF,2.0,0.0,7.0,0.0,2.0,...,0.0,2.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN
651,NaN,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data2[0].to_csv('NBA_2015.csv')

In [ ]:
data2[1]

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,Awards
0,1.0,LeBron James,30.0,CLE,SF,20.0,20.0,844.0,227.0,544.0,...,189.0,226.0,169.0,33.0,21.0,82.0,58.0,601.0,3.0,NaN
1,2.0,Stephen Curry,26.0,GSW,PG,21.0,21.0,826.0,200.0,439.0,...,85.0,105.0,134.0,39.0,3.0,82.0,47.0,594.0,0.0,NaN
2,3.0,James Harden,25.0,HOU,SG,17.0,17.0,636.0,129.0,294.0,...,85.0,97.0,128.0,28.0,7.0,77.0,49.0,462.0,1.0,NaN
3,4.0,Klay Thompson,24.0,GSW,SG,21.0,21.0,761.0,149.0,334.0,...,72.0,81.0,54.0,16.0,19.0,41.0,64.0,391.0,0.0,NaN
4,5.0,Blake Griffin,25.0,LAC,PF,14.0,14.0,557.0,140.0,274.0,...,140.0,178.0,86.0,14.0,14.0,45.0,43.0,357.0,3.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,205.0,Greg Smith,24.0,DAL,PF,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
205,206.0,Russ Smith,23.0,MEM,PG,2.0,0.0,3.0,0.0,0.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
206,207.0,Mirza Teletović,29.0,BRK,PF,3.0,0.0,16.0,0.0,5.0,...,4.0,4.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,NaN
207,208.0,Gerald Wallace,32.0,BOS,SF,1.0,0.0,4.0,0.0,1.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
208,NaN,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN